import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Topbar from "./components/topbar";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
       <main className="max-w-7xl container mx-auto">
       <Topbar/>
        {children}
        <Footer/>
       </main>
          </body>
    </html>
    </ClerkProvider>
  );
}
